apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          set $prometheus_backend "http://prometheus-operated.monitoring.svc.cluster.local:9090";
          proxy_pass $prometheus_backend/api/v1/;
          proxy_read_timeout 120s;
        }

        location /alertmanager/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          set $alertmanager_backend "http://alertmanager-operated.monitoring.svc.cluster.local:9093";
          proxy_pass $alertmanager_backend/api/v2/;
          proxy_read_timeout 120s;
        }  
      }
    }
    pid /tmp/nginx.pid;
