apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  health_check.sh: |
    #!/bin/bash

    if [ "$(curl -s -o /dev/null -w "%{http_code}" http://prometheus-operated.monitoring.svc.cluster.local:9090/-/ready)" -ne 200 ]; then
      exit 1
    fi

    if [ "$(curl -s -o /dev/null -w "%{http_code}" http://alertmanager-operated.monitoring.svc.cluster.local:9093/-/healthy)" -ne 200 ]; then
      exit 1
    fi

    exit 0
  nginx.conf: |
    events {
    }

    http {
      resolver 10.100.0.10 valid=10s;
      error_log /var/log/nginx/error.log debug;
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus/-/ready {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://prometheus-operated.monitoring.svc.cluster.local:9090/-/ready";
          proxy_read_timeout 120s;
        }

        location /prometheus/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/";
          proxy_read_timeout 120s;
        }

        location /alertmanager/-/healthy {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://alertmanager-operated.monitoring.svc.cluster.local:9093/-/healthy";
          proxy_read_timeout 120s;
        }

        location /alertmanager/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/";
          proxy_read_timeout 120s;
        }  
      }
    }
    pid /tmp/nginx.pid;
