apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus {
            if ($request_method !~ ^(GET)$ ) {
            return 405;
            }
            proxy_pass http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/alerts;
        }

      location /alertmanager {
        if ($request_method !~ ^(GET)$ ) {
          return 405;
        }
        proxy_pass http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/alerts;
      }  
      }
    }
    pid /tmp/nginx.pid;