apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  health_check.sh: |
    #!/bin/bash

    if [ "$(curl -s -o /dev/null -w "%{http_code}" http://prometheus-operated.monitoring.svc.cluster.local:9090/-/ready)" -ne 200 ]; then
      exit 1
    fi

    if [ "$(curl -s -o /dev/null -w "%{http_code}" http://alertmanager-operated.monitoring.svc.cluster.local:9093/-/healthy)" -ne 200 ]; then
      exit 1
    fi

    exit 0
  nginx.conf: |
    events {
    }

    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=30s;
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          set $prometheus_backend "http://prometheus-operated.monitoring.svc.cluster.local:9090";
          proxy_pass $prometheus_backend/api/v1/;
          proxy_read_timeout 120s;
        }

        location /alertmanager/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          set $alertmanager_backend "http://alertmanager-operated.monitoring.svc.cluster.local:9093";
          proxy_pass $alertmanager_backend/api/v2/;
          proxy_read_timeout 120s;
        }  
      }
    }
    pid /tmp/nginx.pid;
