apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_passhttp://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/;
        }

        location /alertmanager/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/;
        }  
      }
    }
    pid /tmp/nginx.pid;
