apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cloud-platform-monitoring-alerts
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      resolver 10.100.0.10 valid=10s;
      error_log /var/log/nginx/error.log debug;
      server {
        listen 8080;

        location / {
            return 403;
        }

        location /prometheus/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/";
          proxy_read_timeout 120s;
        }

        location /alertmanager/ {
          if ($request_method !~ ^(GET)$ ) {
            return 405;
          }
          proxy_pass "http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/";
          proxy_read_timeout 120s;
        }  
      }
    }
    pid /tmp/nginx.pid;