apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-alerts-deployment
  namespace: cloud-platform-monitoring-alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-alerts
  template:
    metadata:
      labels:
        app: monitoring-alerts
        app.kubernetes.io/name: cloud-platform-monitoring-alerts
    spec:
      containers:
        - name: monitoring-alerts
          image: nginxinc/nginx-unprivileged:1.26-bookworm
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: health-check-script
              mountPath: /usr/local/bin/health_check.sh
              subPath: health_check.sh
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/health_check.sh
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: health-check-script
          configMap:
            name: nginx-config
            items:
              - key: health_check.sh
                path: health_check.sh
            defaultMode: 0755
