apiVersion: v1
kind: Service
metadata:
  name: monitoring-alerts-service
  namespace: cloud-platform-monitoring-alerts
spec:
  selector:
    app: monitoring-alerts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP